version: "3.8"
services:
  registry-backend:
    image: registry
    container_name: backend-registry
    expose:
      - "5000"
    ports:
      # - target: "5000"
      #  published: "5000"
      #  protocol: tcp
      #  mode: host
      - "5000:5000"
    
    volumes:
      - type: volume
        source: my-registry
        target: /var/lib/registry
        volume:
          nocopy: no
      #- type: bind
      #  source: "$PWD/docker-registry"
      #  target: /var/lib/registry
      #  volume:
      #    nocopy: no
    init: true
    networks:
      registry-network:
    labels:
      maintainer: "Dipayan Pramanik"
      about: "My docker registry"
    restart: unless-stopped



  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2 
    container_name: frontend-registry
    depends_on: 
      - registry-backend
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry-backend
    env_file:
      - ./envfile
    ports:
      - "8080:80"
    networks:
      registry-network:
        aliases:
          - frontend
    labels:
      maintainer: "Dipayan Pramanik"
      about: "My docker registry frontend"
    restart: unless-stopped
    init: true

volumes:
  my-registry:
    name: Image-Registry
    labels:
      maintainer: "Dipayan Pramanik"
      about: "My docker registry volume"

networks:
  registry-network:
    driver: bridge
    labels:
      maintainer: "Dipayan Pramanik"
      about: "My docker registry network"
    name: registry-network
